// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO81CDvcMHbMM_hBm257PVVuJ_M5ETkeQ',
    appId: '1:340057161046:web:2c93874166cb48556faaf7',
    messagingSenderId: '340057161046',
    projectId: 'healthy-hair-routine',
    authDomain: 'healthy-hair-routine.firebaseapp.com',
    storageBucket: 'healthy-hair-routine.appspot.com',
    measurementId: 'G-7GW9TLYRKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGkPlI-IFhQoOkVBRLd00K9QJ0xefBJ5s',
    appId: '1:340057161046:android:8510a07172a757cb6faaf7',
    messagingSenderId: '340057161046',
    projectId: 'healthy-hair-routine',
    storageBucket: 'healthy-hair-routine.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApucX5eX23BCkNVZXLAK3UXT0jEST4atM',
    appId: '1:340057161046:ios:ad773e1c27c58ba56faaf7',
    messagingSenderId: '340057161046',
    projectId: 'healthy-hair-routine',
    storageBucket: 'healthy-hair-routine.appspot.com',
    iosClientId: '340057161046-4ud5u13lpehj5acochf6nt93deur273k.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApucX5eX23BCkNVZXLAK3UXT0jEST4atM',
    appId: '1:340057161046:ios:ad773e1c27c58ba56faaf7',
    messagingSenderId: '340057161046',
    projectId: 'healthy-hair-routine',
    storageBucket: 'healthy-hair-routine.appspot.com',
    iosClientId: '340057161046-4ud5u13lpehj5acochf6nt93deur273k.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterProject',
  );
}
